### ISSUE TITLE
[FEAT] HELP CENTER - SEARCH ARTICLE(s).

### ISSUE THREAD

**Issue by CFCIfe** [hngprojects/hng_boilerplate_nestjs#107]
## Description

This page serves as the central hub for our help center, providing users with access to a wealth of informative articles. With its intuitive search functionality, users can easily find the articles they need to address their questions or concerns. Additionally, the help center page implements rate limiting on its search endpoints.

## Acceptance Criteria

- Articles can be searched for.
- Rate limiting is set on search endpoints.

## Purpose

Users can search for articles by titles / topics.

## Requirements

- [ ] Articles can be searched for.
- [ ] Rate limiting is set.

### [GET] /api/v1/help-center/topics/search?title={title}

**Description**

- Will accept query parameters that would be used to filter the result based on the passed title

**Successful Response**

Status code: 200

```
{
  "success": true,
  "message": "string",
  "status_code": 200
  "topics": [
    {
      "id": "int",
      "title": "string",
      "content": "string",
      "author": "string"
    }
    ...
  ]
}
```

**Error Response**

Status code: 404

**No article matches the title search param.**

```json
{
  "success": false,
  "message": "string",
  "status_code": 404
}
```

Status code: 429

**Too many requests, Rate limit reached.**

```json
{
  "success": false,
  "message": "string",
  "status_code": 429
}
```

Status code: 500

**Internal Server Error**

```json
{
  "success": false,
  "message": "string",
  "status_code": 500
}
```

## Database Schema

**Table name: help_center_topic**

```
- id:
  - constraints: string(uuid), unique, primary-key, not null
- title:
  - constraints: unique, not null, text
- content:
  - constraints: not null, text
- author:
  - constraints: not null, text
- createdAt:
  - constraints: datetime
- updatedAt:
  - constraints: datetime
- user_id:
  - constraints: string(uuid), unique, foreign-key, not null
```

### Database diagram

<img width="233" alt="image" src="https://github.com/user-attachments/assets/b460c15f-9d8c-4b6a-944f-ab639a6744b5">

### Testing

1. Unit Tests

- The system should have unit tests covering rate limit check.
- The return data for the query param in `/api/v1/help-center/topics` matches the documentation.
